import { auth } from "@/lib/auth";
import { 
  CheckSquare, 
  Search, 
  Filter, 
  PlusCircle, 
  Clock, 
  AlertTriangle, 
  Calendar, 
  MessageSquare, 
  Activity,
  ArrowRight
} from "lucide-react";
import { Button, GlassCard } from "@/components/ui/core";
import { Role } from "@prisma/client";
import { redirect } from "next/navigation";

/**
 * Nurse Tasks - Screen 5.
 * Prioritized clinical to-do list auto-generated by the triage system.
 * Focused on clinical urgency (missed appts > overdue logs).
 */
export default async function NurseTasks() {
  const session = await auth();
  if (!session || session.user.role !== Role.NURSE) redirect("/login");

  const TaskCard = ({ type, title, patient, due, priority, source }: any) => (
    <GlassCard className={`!p-0 border-0 shadow-sm relative overflow-hidden group cursor-pointer transition-all hover:translate-x-1 hover:shadow-indigo-100`}>
       <div className={`absolute left-0 top-0 bottom-0 w-1.5 ${priority === 'high' ? 'bg-rose-500' : 'bg-indigo-400'}`} />
       <div className="p-6 pl-8 flex flex-col md:flex-row md:items-center justify-between gap-6">
          <div className="flex items-start gap-4">
             <div className={`w-10 h-10 rounded-xl bg-slate-50 flex items-center justify-center font-bold ${priority === 'high' ? 'text-rose-600' : 'text-slate-400'}`}>
                {source === 'appointment' ? <Calendar className="w-5 h-5" /> : source === 'log' ? <Activity className="w-5 h-5" /> : <MessageSquare className="w-5 h-5" />}
             </div>
             <div>
                <p className={`text-sm font-bold leading-tight ${priority === 'high' ? 'text-rose-900' : 'text-slate-900'} group-hover:text-indigo-600 transition-colors`}>{title}</p>
                <div className="flex items-center gap-3 mt-1.5">
                   <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">{patient}</p>
                   <div className="w-1 h-1 rounded-full bg-slate-300" />
                   <div className="flex items-center gap-1">
                      <Clock className="w-3 h-3 text-slate-400" />
                      <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest leading-none">Due {due}</p>
                   </div>
                </div>
             </div>
          </div>
          <div className="flex items-center gap-3">
             <Button variant="ghost" size="sm" className="h-9 px-4 text-xs font-bold text-slate-400 hover:text-slate-900 border border-slate-100">Add Note</Button>
             <Button variant="secondary" className="h-9 px-4 text-xs font-bold bg-slate-950 hover:bg-black shadow-lg">Complete</Button>
          </div>
       </div>
    </GlassCard>
  );

  return (
    <div className="space-y-8 animate-in fade-in duration-500 pb-20">
      
      {/* Task Header (Section A5) */}
      <div className="flex flex-col md:flex-row md:items-end justify-between gap-4">
         <div>
            <h1 className="text-4xl font-bold font-outfit tracking-tight">Work <span className="text-indigo-600">List</span></h1>
            <p className="text-slate-500 mt-2 font-medium">Auto-generated clinical follow-up priority.</p>
         </div>
         <div className="flex items-center gap-3">
            <Button variant="outline" size="sm" className="h-10 px-4 gap-2 font-bold text-[10px] uppercase tracking-widest border-slate-100">
               <Filter className="w-3.5 h-3.5" /> Filter
            </Button>
            <Button variant="secondary" className="h-10 px-6 gap-2 bg-indigo-600 hover:bg-indigo-700 font-bold text-xs shadow-lg">
               <PlusCircle className="w-4 h-4" /> Create Task
            </Button>
         </div>
      </div>

      {/* Task View Toggle (Section A5) */}
      <div className="flex items-center gap-2 p-1 bg-slate-50 border border-slate-100 rounded-2xl w-fit">
         <button className="px-4 py-2 text-[10px] font-bold uppercase tracking-widest bg-white text-indigo-600 rounded-xl shadow-sm">My Tasks Today</button>
         <button className="px-4 py-2 text-[10px] font-bold uppercase tracking-widest text-slate-400 hover:text-slate-600">All Patient Tasks</button>
         <button className="px-4 py-2 text-[10px] font-bold uppercase tracking-widest text-slate-400 hover:text-slate-600">Completed</button>
      </div>

      {/* Prioritized Task List (Section A5) */}
      <div className="space-y-6">
         
         {/* Urgent Tasks Section */}
         <div className="space-y-4">
            <h3 className="text-sm font-black text-rose-600 uppercase tracking-[0.3em] flex items-center gap-2">
               Urgent Follow-ups
               <AlertTriangle className="w-3.5 h-3.5" />
            </h3>
            <div className="space-y-3">
               <TaskCard 
                  title="Follow up on missed Oncology Clinic appointment" 
                  patient="Patient MRN-982312" 
                  due="Today 17:00" 
                  priority="high" 
                  source="appointment" 
               />
               <TaskCard 
                  title="Symptom Log overdue 3+ days (Critical Gap)" 
                  patient="Patient MRN-112093" 
                  due="Tomorrow 09:00" 
                  priority="high" 
                  source="log" 
               />
            </div>
         </div>

         {/* Routine Tasks Section */}
         <div className="space-y-4 pt-8">
            <h3 className="text-sm font-black text-slate-400 uppercase tracking-[0.3em]">
               Daily Clinical Routine
            </h3>
            <div className="space-y-3">
               <TaskCard 
                  title="Review Cycle 4 Education Engagement" 
                  patient="Patient MRN-449102" 
                  due="Apr 04" 
                  priority="routine" 
                  source="education" 
               />
               <TaskCard 
                  title="Registry: Missing Pathological Histology Code" 
                  patient="Patient MRN-009218" 
                  due="Apr 05" 
                  priority="routine" 
                  source="registry" 
               />
               <TaskCard 
                  title="Follow up on unanswered message thread" 
                  patient="Patient MRN-882103" 
                  due="Today 18:30" 
                  priority="routine" 
                  source="message" 
               />
            </div>
         </div>
      </div>

      {/* Task Insight Strip (Section A5) */}
      <GlassCard className="bg-slate-950 text-white border-0 shadow-2xl overflow-hidden mt-12 relative">
         <div className="absolute right-0 top-0 bottom-0 w-48 opacity-10 flex items-center justify-center p-12 bg-white/10 group">
             <CheckSquare className="w-full h-full scale-150 rotate-12 transition-transform group-hover:scale-[2]" />
         </div>
         <div className="relative z-10 flex flex-col md:flex-row items-center justify-between gap-6">
            <div>
               <p className="text-[10px] font-bold text-indigo-400 uppercase tracking-[0.2em] mb-2">Clinical Completion Rate</p>
               <h4 className="text-2xl font-bold font-outfit leading-tight italic">94% Attendance Follow-up Compliance this week</h4>
               <p className="text-xs text-slate-400 mt-2 font-medium">Highest among Oncology Teams — Keep the streak active.</p>
            </div>
            <Button variant="ghost" className="h-11 px-6 rounded-full border border-white/20 text-white hover:bg-white hover:text-black font-bold gap-2 group">
               View Performance <ArrowRight className="w-4 h-4 group-hover:translate-x-1" />
            </Button>
         </div>
      </GlassCard>
    </div>
  );
}
